name: Codecov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Required for actions/upload-pages-artifact
  pages: write     # Required for actions/deploy-pages
  id-token: write  # Required for actions/deploy-pages

jobs:
  collect:
    name: collect
    if: github.repository == 'aws/aws-cdk'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install

      - name: Build Library
        run: npx lerna run build --scope=aws-cdk-lib

      - name: Run Core tests
        run: cd packages/aws-cdk-lib && yarn test core

      - name: Upload results to Codecov
        if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push'
        uses: codecov/codecov-action@v5
        with:
          files: packages/aws-cdk-lib/coverage/cobertura-coverage.xml
          fail_ci_if_error: true
          flags: suite.unit
          use_oidc: true
      - name: Skip Codecov upload (fork PR)
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: echo "Skipping Codecov upload. PR is from a fork"
